### ISSUE TITLE
Installation error after upgrade to Foundry 11.304

### ISSUE THREAD

**Issue by rklos** [fvtt-fria-ligan/cy_borg-foundry-3p#2]
Hi,
I've got an error in the `cy-borg-3p` module after I've upgraded to foundry 11.304.
Error:
```
[cy-borg-3p] Metadata validation failed for module "cy-borg-3p": The file "/scripts/module.js" included by module cy-borg-3p does not exist
```

After uninstall, I can't install it again because I'm getting an error in the console:
![CleanShot 2023-07-02 at 16 47 49](https://github.com/fvtt-fria-ligan/cyborg-foundry-3p/assets/34719093/4a01f561-3250-4df1-90a0-5b4ce8789749)

@mcglincy

**Comment by greedyj4ck** [comment]
Same issue here.

**Comment by rklos** [comment]
I've made a fix for this issue (#3) @mcglincy

**Comment by mcglincy** [comment]
Thanks so much @rklos ! (I've been swamped with a new job so have been behind on Foundry stuff.)

Merged your PR and released 2.0.1.

**Comment by rklos** [comment]
Ok, unfortunately my fix coped with the "Metadata validation failed" issue only.
The `Cannot read properties of null (reading 'protected')` error is still present :(

@mcglincy

**Comment by greedyj4ck** [comment]
Fix is easy - scripts folder is missing from release module.zip. 

After i downloaded entire repo and unpack it - it works perfectly ;p

**Comment by mcglincy** [comment]
Added ./scripts dir to github workflow. Rebuilt 2.0.2. Can anyone give that a test?

**Comment by rklos** [comment]
Now it works!
